// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvzbkqkiqsznyidsohvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2emJrcWtpcXN6bnlpZHNvaHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTE2MDUsImV4cCI6MjA2NzI2NzYwNX0.YG8f4l2CZwdoWAyI5tV5WOiyVmRtIqCJsqNquFdEByE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});